name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: nwarila-platform/.github/.github/workflows/reusable-iac-security.yaml@1952b49c95a640734a7549a5d748477b7d74792e
